### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by modernpacifist** [Massugunaen/names-changer#9]
- [x] Add separate file with rules of conjugation
- [ ] Add required functions to work with startup list of data, rewrite from "Petrovich" (?)
- [ ] Got a problem if startup data has quotes (") in name list (?)
- [ ] Got a problem if startup data has uppercase in name list (?)
